### ISSUE TITLE
Kommentare nicht Page-Abhängig

### ISSUE THREAD

**Issue by ghost** [Fabiano197/Main#17]
Die selben Kommentare erscheinen bei allen Pages. Bitte abhängig von der Page machen (mit der PageID).

**Comment by Fabiano197** [comment]
Dafür brauche ich erst mal noch den content für mySQL,. Ausserdem ist es fragwürdig, ob es überhaupt Sinn macht, für jedes Kapitel eine eigene Kommentarfunktion zu haben
