### ISSUE TITLE
SQL Datenbank

### ISSUE THREAD

**Issue by Fabiano197** [Fabiano197/Main#2]
Kann jemand von euch ein txt File hochladen mit der SQL Datenstruktur, damit ich diese mit XAMPP simulieren kann?

**Comment by ghost** [comment]
Wiso hochdütsch? xD
ond esch da züg ned scho droffe?

**Comment by Fabiano197** [comment]
tönt mindestens so, als ob mer prfessionell wäred :D ansonste hets de roman erst nach dem issue ufeglade, trotzdem danke ;)
